sudo: false
language: cpp
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-5
            - g++-5
before_install:
    - bash install_deps.sh
    - export CC=gcc-5
    - export CXX=g++-5
    - export PATH="$HOME/deps/cmake/bin":"$PATH"
    - export CMAKE_PREFIX_PATH="$HOME/deps/boost"
cache:
    directories:
        - $HOME/deps
script:
    - mkdir build && cd build && cmake -DBUILD_EXAMPLES=ON -DWITH_IPO=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-Wno-deprecated-declarations .. && make -j2
